### ISSUE TITLE
agg23 vs Spiritualized NES  core differences?

### ISSUE THREAD

**Issue by edrozenberg** [agg23/openfpga-NES#18]
### Ask a question

Just curious if there are any important differences between this `agg23` NES core and the `Spiritualized_NES` core (latest is `Spiritualized_NES_1.0.2_2022_11_08`). I assume both will continue to be developed in parallel?

**Comment by agg23** [comment]
In general, you'll want to use the Spiritualized cores if you want the most fully featured emulation (the only exception will be the SNES core if/when Spiritualized releases it, as the srg320 SNES (my core) supports more special chips than the Analogue one). My cores (and the MiSTer cores they come from) are OSS, so the community can make improvements as necessary, which may be important to you.

There are some other important features covered by Spiritualized that I haven't gotten around to supporting. A partial list:

## Spiritualized

* FDS support
* NSF playback (with one of the best visualizers)
* Loading of external/custom palettes
* Larger list of supported mappers (I can't find a list, but it's the same support as the NT Mini Noir)

## agg23

* OSS, with latest upstream at https://github.com/MiSTer-devel/NES_MiSTer
* Community supported
* Matter of opinion, but the AR is correct, rather than being locked at 4:3 (to be fair, you can manually edit `video.json` in the Spiritualized core to correct this)
* Lightgun/zapper support
* Eventually will support save states (I've been stuck on this)

Obviously the Spiritualized core is the one to go with unless you value the OSS aspect. Features like FDS and NSF playback should come to this core in the future, but I'm not very interested in working on them right now. This core will definitely be one to consider once save state support comes, as the Spiritualized core will likely never support it.

**Comment by edrozenberg** [comment]
@agg23 thank you for the great comparison of the features of the 2 cores, and for the NES and SNES cores.

I'm a big fan/user of MiSTer as well, and it's great to hear these cores come from there. Huge respect for the accuracy and features of MiSTer cores.

Save state support will definitely be a big reason to use this core if it comes, and the lightgun supports sounds interesting though I haven't tried it yet.

Trying 11:9 (based on suggestion from https://github.com/libretro/RetroArch/issues/2837) on the Spiritualized NES core video.json and that looks good to me and fills the Pocket screen better, though some CRT YT footage looks more like the 4:3. I know with SNES it's game-specific and it's great that the agg core makes it easy to switch 4:3 on/off - I landed on 4:3 ON being better w/Chronotrigger, but OFF with Ghouls 'n Ghosts for example.

**Comment by agg23** [comment]
Wanted to call out that save states are now available with 0.3.1, and I edited my comment above to reflect that

**Comment by edrozenberg** [comment]
> Wanted to call out that save states are now available with 0.3.1, and I edited my comment above to reflect that

That's great news thank you! I'll try it out soon.
