### ISSUE TITLE
Scanlines or other CRT effects?

### ISSUE THREAD

**Issue by eobet** [agg23/openfpga-NES#39]
### Ask a question

The "native" cores have various wonderful video effects, but I don't think this core has any?

Even changing pixel format, resolution and coverage has to be done via a .json file currently...

What are the chances things could be done in this area, like:

- Simple 100%, 75%, 50%, 25% scanlines
- More advanced CRT effects with bloom, bleed and bevel?

**Comment by agg23** [comment]
None of the openFPGA cores have settings like that. The way the Pocket is designed, the second FPGA operates the scaler and applies any effects necessary. This functionality is not yet available to openFPGA cores.

It's been a while since I've received advanced info, but when I last heard, this coming Pocket update (supposed to be before the end of the year) will contain the video modes for openFPGA.

----

In any case, this core is completely out of space; currently at 99% utilization (you're not really supposed to go over ~80). There's no room to add advanced effects or post processing.

**Comment by eobet** [comment]
@agg23 with Pocket firmware 2.0 you can apparently now enable different CRT effect modes...

**Comment by agg23** [comment]
Trinitron mode does indeed have scanlines. It forces integer scaling, hence the smaller picture. I believe the Integer+ mode will come closer to filling the screen.

**Comment by naveedster** [comment]
Yes! I noticed it too. Thank you Adam
